### ISSUE TITLE
support macOS (and others?)

### ISSUE THREAD

**Issue by ellio167** [conda-forge/kimpy-feedstock#4] opened 2019-11-08 16:13 UTC
https://github.com/conda-forge/kimpy-feedstock/blob/c4ea5d2c42e2927646354df65ba799ffe9ba98bf/recipe/meta.yaml#L14

Should we change this so that systems other than linux are supported?

**Comment by jan-janssen** [comment] 2019-11-08 18:35
I just tired it with he newly compiled kim-api but it still fails https://github.com/conda-forge/kimpy-feedstock/pull/5

**Comment by ellio167** [comment] 2019-11-08 18:50
Ah, it  looks like it needs a build-time dependency on `pkgconfig`

**Comment by jan-janssen** [comment] 2019-11-08 20:44
I tried adding pkgconfig, but it seems the issue is that it does not find the library. https://github.com/conda-forge/kimpy-feedstock/pull/5/commits/dbaa6d1d3b3809c72aba6b74f404cb963fbfdae2

**Comment by ellio167** [comment] 2019-11-08 21:34
Sorry, it needs the binary pkg-config package, not the python interface to the binary package.  On conda I guess that is `pkg-config` not `pkgconfig`.

**Comment by jan-janssen** [comment] 2019-11-09 02:18
Thanks a lot, I was not aware of this difference. Mac OS support is added now. If we also want windows support I guess we have to check kim-api package first. Do you commonly build Windows binaries using visualstudio - that is the default compiler on conda-forge for Windows?

**Comment by jan-janssen** [comment] 2019-11-09 02:36
By the way I noticed that `openkim-models` still has issues to recognize clang as c compiler - https://github.com/conda-forge/openkimmodels-feedstock/pull/7

**Comment by ellio167** [comment] 2019-11-09 03:50
The kim-api does not currently work on Windows.  So, we'll have to leave that out for now.

**Comment by jan-janssen** [comment] 2019-11-09 12:45
I merged https://github.com/conda-forge/openkimmodels-feedstock/pull/7 so I guess we can close this issue now.

**Closed as completed** 2019-11-09 15:10 UTC
